-- 板情報を保存するテーブル(学習用)
CREATE TABLE boards (
    id INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    stock_code VARCHAR(4) NOT NULL COMMENT '証券コード',
    market_code VARCHAR(1) NOT NULL COMMENT '市場コード (1: 東証、3: 名証、5: 福証、6: 札証)',
    price FLOAT(7,1) DEFAULT NULL COMMENT '現在株価',
    latest_transaction_time DATETIME DEFAULT NULL COMMENT '直近約定時刻',
    change_status VARCHAR(2) NOT NULL COMMENT '一取引前からのステータス変動 (00: 存在しない、56: 変動なし、57: 上昇、58: 下落、59: 中断板寄り後の初値、60: ザラ場引け、61: 板寄せ引け、62: 中断引け、63: ダウン引け、64: 逆転終値、66: 特別気配引け、67: 一時留保引け、68: 売買停止引け、69: サーキットブレーカ引け)',
    present_status VARCHAR(2) NOT NULL COMMENT '現在のステータス (1: 現在値で取引成立、2:不連続歩み、3: 板寄せ、4: システム障害、5: 中断、6: 売買停止、7: 売買停止解除・システム停止解除、8: 終値で取引成立、9: システム停止、10: 概算値、11: 参考値、12: サーキットブレイク発動中、13:システム障害解除、14: サーキットブレイク解除、15: 中断解除、16: 一時保留中、17: 一時保留解除、18: ファイル障害、19: ファイル障害解除、20: Spread/Strategy、21: ダイナミックサーキットブレーク発動中、22: ダイナミックサーキットブレーク解除、23: 板寄せ約定)',
    market_buy_qty BIGINT(11) NOT NULL COMMENT '買成行注文の株数',
    buy1_sign VARCHAR(3) NOT NULL COMMENT '買い気配フラグ(000: 事象なし、101: 一般気配、102: 特別気配、103: 注意気配、107: 寄前気配、108: 停止前特別気配、0109: 引け後気配、116: 寄前気配約定成立ポイントなし、117: 寄前気配約定成立ポイントあり、118: 連続約定気配、119: 停止前の連続約定気配、120: 買い上がり売り下がり中)',
    buy1_price FLOAT(9,1) DEFAULT NULL COMMENT '1番目に高い買い注文価格',
    buy1_qty BIGINT(11) DEFAULT NULL COMMENT '1番目に高い買い注文価格の株数',
    buy2_price FLOAT(9,1) DEFAULT NULL COMMENT '2番目に高い買い注文価格',
    buy2_qty BIGINT(11) DEFAULT NULL COMMENT '2番目に高い買い注文価格の株数',
    buy3_price FLOAT(9,1) DEFAULT NULL COMMENT '3番目に高い買い注文価格',
    buy3_qty BIGINT(11) DEFAULT NULL COMMENT '3番目に高い買い注文価格の株数',
    buy4_price FLOAT(9,1) DEFAULT NULL COMMENT '4番目に高い買い注文価格',
    buy4_qty BIGINT(11) DEFAULT NULL COMMENT '4番目に高い買い注文価格の株数',
    buy5_price FLOAT(9,1) DEFAULT NULL COMMENT '5番目に高い買い注文価格',
    buy5_qty BIGINT(11) DEFAULT NULL COMMENT '5番目に高い買い注文価格の株数',
    buy6_price FLOAT(9,1) DEFAULT NULL COMMENT '6番目に高い買い注文価格',
    buy6_qty BIGINT(11) DEFAULT NULL COMMENT '6番目に高い買い注文価格の株数',
    buy7_price FLOAT(9,1) DEFAULT NULL COMMENT '7番目に高い買い注文価格',
    buy7_qty BIGINT(11) DEFAULT NULL COMMENT '7番目に高い買い注文価格の株数',
    buy8_price FLOAT(9,1) DEFAULT NULL COMMENT '8番目に高い買い注文価格',
    buy8_qty BIGINT(11) DEFAULT NULL COMMENT '8番目に高い買い注文価格の株数',
    buy9_price FLOAT(9,1) DEFAULT NULL COMMENT '9番目に高い買い注文価格',
    buy9_qty BIGINT(11) DEFAULT NULL COMMENT '9番目に高い買い注文価格の株数',
    buy10_price FLOAT(9,1) DEFAULT NULL COMMENT '10番目に高い買い注文価格',
    buy10_qty BIGINT(11) DEFAULT NULL COMMENT '10番目に高い買い注文価格の株数',
    market_sell_qty BIGINT(11) NOT NULL COMMENT '売成行注文の株数',
    sell1_sign VARCHAR(3) NOT NULL COMMENT '売り気配フラグ(000: 事象なし、101: 一般気配、102: 特別気配、103: 注意気配、107: 寄前気配、108: 停止前特別気配、0109: 引け後気配、116: 寄前気配約定成立ポイントなし、117: 寄前気配約定成立ポイントあり、118: 連続約定気配、119: 停止前の連続約定気配、120: 買い上がり売り下がり中)',
    sell1_price FLOAT(9,1) DEFAULT NULL COMMENT '1番目に安い売り注文価格',
    sell1_qty BIGINT(11) DEFAULT NULL COMMENT '1番目に安い売り注文価格の株数',
    sell2_price FLOAT(9,1) DEFAULT NULL COMMENT '2番目に安い売り注文価格',
    sell2_qty BIGINT(11) DEFAULT NULL COMMENT '2番目に安い売り注文価格の株数',
    sell3_price FLOAT(9,1) DEFAULT NULL COMMENT '3番目に安い売り注文価格',
    sell3_qty BIGINT(11) DEFAULT NULL COMMENT '3番目に安い売り注文価格の株数',
    sell4_price FLOAT(9,1) DEFAULT NULL COMMENT '4番目に安い売り注文価格',
    sell4_qty BIGINT(11) DEFAULT NULL COMMENT '4番目に安い売り注文価格の株数',
    sell5_price FLOAT(9,1) DEFAULT NULL COMMENT '5番目に安い売り注文価格',
    sell5_qty BIGINT(11) DEFAULT NULL COMMENT '5番目に安い売り注文価格の株数',
    sell6_price FLOAT(9,1) DEFAULT NULL COMMENT '6番目に安い売り注文価格',
    sell6_qty BIGINT(11) DEFAULT NULL COMMENT '6番目に安い売り注文価格の株数',
    sell7_price FLOAT(9,1) DEFAULT NULL COMMENT '7番目に安い売り注文価格',
    sell7_qty BIGINT(11) DEFAULT NULL COMMENT '7番目に安い売り注文価格の株数',
    sell8_price FLOAT(9,1) DEFAULT NULL COMMENT '8番目に安い売り注文価格',
    sell8_qty BIGINT(11) DEFAULT NULL COMMENT '8番目に安い売り注文価格の株数',
    sell9_price FLOAT(9,1) DEFAULT NULL COMMENT '9番目に安い売り注文価格',
    sell9_qty BIGINT(11) DEFAULT NULL COMMENT '9番目に安い売り注文価格の株数',
    sell10_price FLOAT(9,1) DEFAULT NULL COMMENT '10番目に安い売り注文価格',
    sell10_qty BIGINT(11) DEFAULT NULL COMMENT '10番目に安い売り注文価格の株数',
    over_qty BIGINT(11) NOT NULL COMMENT 'OVER注文株数',
    under_qty BIGINT(11) NOT NULL COMMENT 'UNDER注文株数',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'レコード追加時刻',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;